### ISSUE TITLE
spot api throwing timeout exception

### ISSUE THREAD

**Issue by marif4444** [gateio/gateapi-python#1]
HTTP response body: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

**Comment by marif4444** [comment]
@revilwang  @gateio need a fix ASAP

**Comment by revilwang** [comment]
Please provide more details about where you send the request from, which request you send and whether it happens all the time

**Comment by revilwang** [comment]
It's a server issue and should be fixed by now.
