### ISSUE TITLE
Can't access the balance with ccxt

### ISSUE THREAD

**Issue by AqueousCarlos** [gateio/gateapi-python#103]
I have already granted the right of READ and WRITE on my APIv4 without white IP address list. After Run the below code: 
My request no.  in gate.io support is 827908

```
import ccxt
gateio_spot = ccxt.gateio({
    'apiKey': 'XXXXX',
    'secret': 'XXXXXX',
})

print(gateio_spot.fetch_balance())
```

I got the below error message:
`ccxt.base.errors.AuthenticationError: Invalid sign`

Please kindly help. Thank a lot.

**Comment by revilwang** [comment]
Have you tried using the demo python snippet in the [API reference](https://www.gate.io/docs/developers/apiv4/en/#list-spot-accounts)? If you can run the snippet without any error, I think you should contact cctx with this issue.
