### ISSUE TITLE
Can't borrow money for margin trading

### ISSUE THREAD

**Issue by MeronnSapir** [gateio/gateapi-python#104]
Hi, I am looking to margin trading via the api.
I read the previous questions about it and based on the answers I found that no matter what the currency is, the amount of available borrowable money from gate_io is 0 (based on margin_api.get_margin_borrowable).
I saw that there is a borrow limit of 100K per currency, but it is quite weird to me that after checking 20 relatively small coins none of them had a borrowable amount.
Are all of them really fully borrowed or can't we borrow anymore from the api?
thank you very much!
Meronn

**Comment by revilwang** [comment]
The borrow limit policy has been updated recently, and API is catching on with it. We'll update it as soon as the work is done.

But besides this, there is also a market limit. Once reached, no one can borrow from the market, which can also leads to your max borrowable to be 0.

**Comment by MeronnSapir** [comment]
Alright thanks!
How can I stay updated about that?
Is asking here once in a while (about a week) is fine?

**Comment by revilwang** [comment]
I'll update the issue once it's done

**Comment by revilwang** [comment]
It has been fixed quite a while ago. I'll close the issue.
