### ISSUE TITLE
有接口查询永续合约的点卡吗

### ISSUE THREAD

**Issue by pumpthis** [gateio/gateapi-python#11]
有接口查询永续合约的点卡吗？

**Comment by revilwang** [comment]
刚刚推送的4.7.2 的版本在合约账户信息和头寸信息里都添加了点卡相关的信息，更新下 SDK 就可以使用了

**Comment by revilwang** [comment]
接口文档，除了 SDK 本身的文档以外，还可以在这里查看原始的 API 文档信息：

[English version](https://www.gateio.co/docs/apiv4/en/index.html)
[中文版](https://www.gateio.co/docs/apiv4/zh_CN/index.html)

**Comment by pumpthis** [comment]
谢谢 已经接入这个接口了
