### ISSUE TITLE
is there any api to serve us coins contract addresses? What is the unique identifier of coins(except currency)?

### ISSUE THREAD

**Issue by medinemerveinan** [gateio/gateapi-python#111]

**Comment by revilwang** [comment]
Please provide more details about your request, such as what is your purpose and how current API cannot meet your requirements

**Comment by medinemerveinan** [comment]
for example  ejs coin ejs and ejs_eth in gateio . I want to find contract addresses of this coins on different platforms from gate.io services.
For ejs :
etherium: 0x96610186f3ab8d73ebee1cf950c750f3b1fb79c2
binance-smart-chain: 0x09f423ac3c9babbff6f94d372b16e4206e71439f
So Is there any way to give contract addresses ?

**Comment by revilwang** [comment]
No, we don't have such APIs. But for the second question, the unique identifier is coin itself if you perform other coin related trades. ejs_eth only provides wallet related status.
