### ISSUE TITLE
currency_ pairs api base info

### ISSUE THREAD

**Issue by medinemerveinan** [gateio/gateapi-python#113]
When i call  '/spot/currency_pairs' api it returns pairs with base info. I want to learn currency information. 
For example ;
I want to give EJS and EJS_ETH currencies pairs. Have they same pairs according to base 'EJS'? 
 Is there any formula between base and currency ? or
 Is there any api that returns currencies pairs?

**Comment by revilwang** [comment]
`/spot/currency_pairs` returns currency pair list. I don't know if I understand your question clearly, but when you say `EJS` or `EJS_ETH`, are you referring to currency info returned from `/spot/currencies`? If so, they means the same currency when you trade, the difference just tells [EJS has multiple chain support](https://www.gate.io/docs/developers/apiv4/en/#list-all-currencies-details). The only currency pair to trade with EJS is `EJS_USDT`(at the time of this comment) returned from the `/spot/currency_pairs`.
