### ISSUE TITLE
Missing fee attribute in LedgerRecord 

### ISSUE THREAD

**Issue by elier** [gateio/gateapi-python#114]
When retrieving withdrawals, the return LedgerRecord doesn't have the 'fee' attribute. 
```
api_instance = gate_api.WalletApi(api_client)
withdrawals = api_instance.list_withdrawals(currency=currency, _from=_from, to=to, limit=limit, offset=offset)
for w in withdrawals:
  print(w)
```
The documentation says it is optional, but that's an important information about the withdraw. Actually, the fee information is displayed in the UI.

**Comment by revilwang** [comment]
Can you send your user id and example withdrawal record IDs which don't have fee returned to dev@mail.gate.io 

We'll check the details for you.
