### ISSUE TITLE
Leverage Issue

### ISSUE THREAD

**Issue by kasahh** [gateio/gateapi-python#117]
Updating leverage using "update_dual_mode_position_leverage" changes the leverage from Cross to Isolated. I want it to remain in Cross mode when I update the leverage but using either "leverage" or "cross_leverage_limit" variables yield the same result. What could be the problem?

**Comment by revilwang** [comment]
If you update `leverage` to non-zero value, the leverage will be changed to Isolated. To remain in cross leverage, you have to set the `leverage` to 0, then set `cross_leverage_limit` to other non-zero values to set  you cross leverages.

I don't know if this answers your question. If so, please provide more details about the problem you encountered.

**Comment by kasahh** [comment]
that worked for me. thanks
