### ISSUE TITLE
Real name of currency

### ISSUE THREAD

**Issue by carasino007** [gateio/gateapi-python#118]
**MARKET SPOT**
how find a real name of currency? example "GT"
I try **GET /spot/currencies/{currency}** and i obtain this: 
_{
  "currency": "GT",
  "delisted": false,
  "withdraw_disabled": false,
  "withdraw_delayed": false,
  "deposit_disabled": false,
  "trade_disabled": false,
  "chain": "GT"
}_
But no appear the real name "GateToken", any can help me?

**Comment by revilwang** [comment]
try WalletApi.withdraw_status
