### ISSUE TITLE
杠杆交易撤单 'Cancel order too fast, please wait 1 min and try again.'

### ISSUE THREAD

**Issue by pumpthis** [gateio/gateapi-python#12]
我在币币交易15个品种上做市挂单，杠杆交易7个品种上做市挂单
挂单撤单的策略和频率应该是一样差不多的
然后 币币交易的所有品种 撤单都没有超频率限制，但是杠杆交易的品种 昨晚开始 一直返回{'label': 'METHOD_NOT_ALLOWED', 'message': 'Cancel order too fast, please wait 1 min and try again.'}

**Comment by pumpthis** [comment]
@revilwang

**Comment by pumpthis** [comment]
昨晚之前都正常的

**Comment by revilwang** [comment]
用户ID烦请提供下

另外只有杠杆的被限制了，现货的没有被限制？还有被限制的是单个订单的撤下操作，还是批量的撤销操作？

**Comment by pumpthis** [comment]
2541076 只有杠杆被限制 现货没有被限制 接口是用的 delete '/api/v4/spot/orders'

**Comment by pumpthis** [comment]
每个品种大概每分钟撤单5~20次 行情最大时候大概每分钟50次 不可能更多了 昨晚之前全都正常的 昨晚开始出现这种限频

**Comment by pumpthis** [comment]
我这个号的币币做到VIP10了...我另一个号ynxrick 合约每个月也有一万多btc的交易量...

**Comment by pumpthis** [comment]
接口 是杠杆账户的批量撤单

**Comment by revilwang** [comment]
后台确认了下，你这边应该只是刚好在杠杆撤单是被限制了。

限制是按用户ID来累计的，1min 内所有撤单请求（包括所有币种的币币和杠杆）如果超过 1k 次，就会被限制

鉴于用户操作可能会频繁，我们将这个限制调整到了 2000 次

**Comment by pumpthis** [comment]
好的 感谢 我尽量也缩减掉一些特小币种的做市...
