### ISSUE TITLE
The Spot post order api not support type of market 

### ISSUE THREAD

**Issue by zksfyz** [gateio/gateapi-python#121]
Hi , The gate.io api of Spot that post order api not support market deal.

1.REST API, https://www.gate.io/docs/developers/apiv4/zh_CN/#%E4%B8%8B%E5%8D%95
![image](https://user-images.githubusercontent.com/11324813/177671615-6ae1c6b4-69da-46fd-a824-35f730948a43.png)

**Comment by revilwang** [comment]
Market order will not be supported at the moment.

**Comment by unkindypie** [comment]
As I understand now market orders are supported and it's possible to create them from the UI, while the SDK still doesn't allow doing it. Any updates?

**Comment by MITATED** [comment]
The gate.io support says nothing about the api. Therefore, I hope that API developers will be able to see here that users need market orders.

**Comment by revilwang** [comment]
It’s on the way and will be supported mostly in the next api version update

**Comment by MITATED** [comment]
Are there any deadlines when our team will be able to count on market-orders?

**Comment by revilwang** [comment]
Spot market order support have been updated. The new 4.34.0 version contains the latest update
