### ISSUE TITLE
how to create an order without specifying the quantity in the spot

### ISSUE THREAD

**Issue by L1de** [gateio/gateapi-python#125]
Hello. How to create an order without specifying the number of coins that I want to buy in the spot. Python

**Comment by revilwang** [comment]
No, this is required. What is your situation to not require coin amount?

**Comment by L1de** [comment]
I need exactly $50 to buy coins at market value
I can do this in an app, but it doesn't work in Python.

**Comment by L1de** [comment]
Do you know any solution to the problem?

**Comment by revilwang** [comment]
A simple calculation will solve your problem. Let's say you pay 50 USDT to buy coin ETH. Retrieve the latest price using `SpotApi.list_tickers(currency_pair='ETH_USDT')[0].last` (call it P), you get order amount with `str(decimal.Decimal(50)/decimal.Decimal(P))`. App does the same thing before placing your order.

**Comment by L1de** [comment]
What if the coin market suddenly rises sharply by 0.1$ up and our order does not work or partially works? New orders will be bought in the application, but probably not here

**Comment by revilwang** [comment]
You can adjust the price according to your need. Yes, it happens, but placing orders using app will encounter the same issue, as it uses the same logic when matching orders.

**Comment by L1de** [comment]
Okay, thanks
