### ISSUE TITLE
list_positions() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by bairavand** [gateio/gateapi-python#128]
```
for asset in ['btc', 'usdt']:
    self.gateio_client.list_positions(asset)
```

**Comment by kasahh** [comment]
That's because you passed in 'btc'.  Your settle should be just 'usdt'. It will then list all your open positions against usdt such as 'btc_usdt', 'eth_usdt' e.t.c

**Comment by bairavand** [comment]
> That's because you passed in 'btc'.  Your settle should be just 'usdt'. It will then list all your open positions against usdt such as 'btc_usdt', 'eth_usdt' e.t.c  You can then filter the results to get the pairs you need.

Thanks for the reply. Even If I pass 'btc' it should return the specific exception. But it says like I'm passing wrong no.of args. Why?

**Comment by revilwang** [comment]
Can you provide your more code context, e.g. how `gateio_client` is initialized?

**Comment by bairavand** [comment]
> Can you provide your more code context, e.g. how `gateio_client` is initialized?

configuration = gate_api.Configuration()
configuration.key = self.api_key
configuration.secret = self.api_secret
return gate_api.FuturesApi(gate_api.ApiClient(configuration))

**Comment by revilwang** [comment]
I've tried the following code, no issue occurred. What is your SDK version?

```python
>>> import gate_api
>>> configuration = gate_api.Configuration()
>>> configuration.key = 'xxx'
>>> configuration.secret = 'xxx'
>>> api_client = gate_api.FuturesApi(gate_api.ApiClient(configuration))
>>> for settle in ('btc', 'usdt'): print([x.contract for x in api_client.list_positions(settle)])
...
['BTC_USD', 'BNB_USD']
['BTC_USDT', 'ETH_USDT']
```

**Comment by bairavand** [comment]
"SDK Package Version: 4.24.0"

**Comment by revilwang** [comment]
Can you reproduce the issue using the code I provided?

**Comment by bairavand** [comment]
With this code, it's working fine.

**Comment by revilwang** [comment]
Then I presume you should inspect your own code

**Comment by bairavand** [comment]
Will do. Thanks for your support
