### ISSUE TITLE
possible issue with list_futures_candlesticks

### ISSUE THREAD

**Issue by sanJuan2021** [gateio/gateapi-python#129]
settle = 'usdt'
contract = 'BTC_USDT'
api_response = api_instance.list_futures_candlesticks(settle, contract, interval='1h')

returns data. But the following call doesn't return anything:

api_response = api_instance.list_futures_candlesticks(settle, contract, interval='1h',to = 1546935600)

to = 1546935600 is taken from code sample.

**Comment by revilwang** [comment]
API only returns the latest 30d's data. `to` is too old. It is an example value, you can replace it to any other time in recent 30 days.

**Comment by sanJuan2021** [comment]
So this function cannot be used to pull historical data?

**Comment by revilwang** [comment]
You can download history data from https://www.gate.io/developer/historical_quotes

**Comment by sanJuan2021** [comment]
Ok. Can you tell me what's the meaning of the "size" column in the candlestick charts?

**Comment by revilwang** [comment]
Total number of contracts traded during one interval. It has the same meaning with the `size` in a futures order.
