### ISSUE TITLE
Transfer api不可用

### ISSUE THREAD

**Issue by milabobo** [gateio/gateapi-python#13]
您好，我参照github上gateio-python的api进行spot到margin的划转操作，提示404 not found
https://github.com/gateio/gateapi-python/blob/937548602284c1a7a0192b1eef0e882520b7441c/gate_api/models/transfer.py

参数和请求：
post /api/v4/wallet/transfers params={'currency': 'USDT', 'currency_pair': 'ETH_USDT', 'amount': '51', '_from': 'spot', 'to': 'margin’}

响应：
Get a error on http POST request for url https://api.gateio.ws/api/v4/wallet/transfers, HTTP 404: Not Found b'{"label":"NOT_FOUND"}\n’

请问是哪里设置的不对吗，还是这个api没有上线？

**Comment by milabobo** [comment]
@revilwang 好的，谢谢，希望尽快上线，需求强烈！

**Comment by eepaul** [comment]
> /wallet 的接口暂未对外开放，还请谅解，具体开放时间在沟通中

现在好像还是404，还没有对外开放吗？
