### ISSUE TITLE
Plese help! Need Stop-Limit aka OCO

### ISSUE THREAD

**Issue by gubinsergey** [gateio/gateapi-python#131]
![2022-08-25_11-35-53](https://user-images.githubusercontent.com/38642138/186608668-0f5f3463-0bd6-4b88-8d84-d6fe5fd033e7.png)
Hi
By WEB a can make this order. How to make it by API? 

I tryed to get info abot this order. This has no info abot stop-loss trigger/ Only take-profit.
![2022-08-25_12-57-52](https://user-images.githubusercontent.com/38642138/186609006-5ea7723a-2c2e-4b90-b1f9-b36b94577965.png)

Who knows where read examples or get info how to make "double-stop-sell-orders"

**Comment by gubinsergey** [comment]
![2022-08-25_15-03-21](https://user-images.githubusercontent.com/38642138/186610041-04a941f7-7156-4a12-a2e7-3a5f8c353d99.png)

**Comment by revilwang** [comment]
This feature is not supported in API requests for now.

**Comment by revilwang** [comment]
But you can create two price orders with different triggers to achieve the same thing.  Refer to #130

**Comment by gubinsergey** [comment]
> But you can create two price orders with different triggers to achieve the same thing. Refer to #130

Thank you!
