### ISSUE TITLE
Amend price trigger order

### ISSUE THREAD

**Issue by Hank421Chen** [gateio/gateapi-python#133]
PUT /futures/{settle}/orders/{order_id}
It looks like this API can only update normal orders.
Is there any way to update trigger orders.
Instead of cancelling price trigger orders and then create new price trigger orders.
Thanks.

**Comment by revilwang** [comment]
No, price trigger orders cannot be modified. You can only cancel then create.

**Comment by Hank421Chen** [comment]
> No, price trigger orders cannot be modified. You can only cancel then create.

I see. Thanks a lot for your quick reply.
