### ISSUE TITLE
Perpetual/Delivery contracts: fee rate fields

### ISSUE THREAD

**Issue by LKresta** [gateio/gateapi-python#135]
[Re-posting https://github.com/gateio/rest-v4/issues/15 here per https://github.com/gateio/gatews/issues/37#issuecomment-1241680493]

Hello there,

I'd like to ask about fee rate fields in https://www.gate.io/docs/developers/apiv4/en/#contract. There are two fee rate fields, maker_fee_rate and taker_fee_rate. What is their semantics, are they just fees effective for current trade (identified by trade_id field)? Or are they in any way related to fees effective for my user account (https://www.gate.io/fee)?

Cheers,
L.

**Comment by revilwang** [comment]
Just ignore them. It's the default fee rate. Your own fee rate should be retrieved using `/wallet/fee` which returns your own futures maker and taker fee(your VIP level is considered)

**Comment by LKresta** [comment]
Ok, thanks for the clarification!
