### ISSUE TITLE
Futures Price Triggered Order

### ISSUE THREAD

**Issue by reddigszymon** [gateio/gateapi-python#136]
Hello, I am unable to create a futures price triggered order, the error i get is

HTTP response body: {"label":"AUTO_INVALID_PARAM_TRIGGER_RULE","message":"invalid argument: Trigger.rule"}

I am trying to create a TAKE PROFIT and a STOP LOSS position.

The code I am using to do it is as follows:

initial = FuturesInitialOrder(contract='OP_USDT', price="0")
trigger = FuturesPriceTrigger(strategy_type=0, price_type=1, price="2", rule=1)

futures_price_triggered_order = FuturesPriceTriggeredOrder(initial=initial, order_type="close-long-order", trigger=trigger)
order_response = futures_api.create_price_triggered_order(settle, order)

Can anyone please guide me as to why is it not working? Or show me some example code how to set it up properly?

**Comment by revilwang** [comment]
The parameter you pass into `futures_api.create_price_triggered_order` should be `futures_price_triggered_order`, not `order` which is nowhere to be found
