### ISSUE TITLE
Perpetual/Delivery contracts: "quanto_multiplier":"0"

### ISSUE THREAD

**Issue by LKresta** [gateio/gateapi-python#137]
Hello there,

https://www.gate.io/docs/developers/apiv4/en/#create-a-futures-order says `quanto_multiplier` determines _how much currency 1 size contract represents_. There are cases where `"quanto_multiplier":"0"`, e.g. in https://api.gateio.ws/api/v4/delivery/btc/contracts. Seems to be the case for inverse contracts where the quote currency is USD. How to determine how much currency 1 contract is in such case? Always 1 USD? Can this (`"quanto_multiplier":"0"`) happen for other currencies as well?

Thanks,
L.

**Comment by revilwang** [comment]
When it's 0, this field does not take effect at all. In such case, 1 contract is always 1 USD.
