### ISSUE TITLE
USER_NOT_FOUND on the testnet

### ISSUE THREAD

**Issue by LKresta** [gateio/gateapi-python#138]
Hello there,
I'm testing [getting all positions](https://www.gate.io/docs/developers/apiv4/en/#list-all-positions-of-a-user) using https://fx-api-testnet.gateio.ws/api/v4 and I'm getting USER_NOT_FOUND as a response. I'm querying `/futures/usdt/positions` in particular and per 'my account' ("Classic account" -> "Contract account" -> "Futures" ) I have funds available there (USDT 'available balance' > 0).

Should this work on testnet? If so, could you please advise as to where to transfer funds to make this work on testnet?

Thanks,
L.

**Comment by revilwang** [comment]
You need to perform transferals on futures testnet web entry, create APIv4 futures TESTNET key, and then access fx-api-testnet using your TESTNET key pair.

**Comment by LKresta** [comment]
Thanks for the response. I do have TESTNET key pair: created on https://www.gate.io/myaccount/apiv4keys - I have the "Testnet APIv4 Keys" section there. So far so good. But I was unable to find anything TESTNET-related in transferrals area. Can you clarify what do you mean by _futures testnet web entry_/pass a link?

**Comment by revilwang** [comment]
Click the funds transfer button shown in the picture. You can add at most 1000 USDT to your testnet account per day.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/8424970/192956836-8fdd3a4b-1ac5-4bdb-9401-e1d4796a9edb.png">

**Comment by LKresta** [comment]
Splendid! Found it, transferred stuff, got it working. Thanks a lot!!
