### ISSUE TITLE
Errors: Your order size 2 is too small. The minimum is 1 USDT

### ISSUE THREAD

**Issue by akashc-25** [gateio/gateapi-python#139]
I am using the Python SDK for my App to buy and sell Crypto. So, I‘m calling the API to buy the ALEPH USDT crypto.

- What I am following is the below,
1. I'm configuring the API_KEY and API_SECRET_KEY
          
          config = Configuration(key=<API_KEY>, secret=<API_SECRET>, host=<GATEIO HOST>)
          SpotApi(ApiClient(config))

2.  I then use the get currency pair API to retrieve the ALEPH USDT currency pair. I am obtaining the min quote amount value from the pair.

          pair = spot_api.get_currency_pair("ALEPH USDT")
          pair.min_quote_amount

         {
            "id": "ALEPH_USDT",
            "base": "ALEPH",
            "quote": "USDT",
            "fee": "0.2",
            "min_quote_amount": "1",
            "amount_precision": 3,
            "precision": 5,
            "trade_status": "tradable",
            "sell_start": 0,
            "buy_start": 0
        },

        I'm taking the 1 as min_quote_amount.

3. Next, I am calling the list_tickers API to get the last price of the currency.
      
          tickers = spot_api.list_tickers(currency_pair=bot.currency_pair)
          tickers[0].last

          tickers[0].last returning the 0.1149 value.

4. After that, I am initializing the Order class by passing the necessary values.
          
          currency = bot.currency_pair.split("_")[1]   => USDT (In this case)
          order_amount = D(min_amount) * 2 => 2
          order = Order(amount=str(order_amount), price=0.1149, side='buy', currency_pair=ALEPH_USDT)       
         
          returning the order object

5. Then I am calling the create_order.
          
          spot_api.create_order(order)

          It is giving me the error saying that "Your order size 2 is too small. The minimum is 1 USDT".

Can anybody please assist me with this?   

I'm assuming that because ALEPH USDT crypto isn't returning the min base amount, some internal conditions aren't satisfied. Is this the cause of the above problem or is there another factor that I am missing?

**Comment by revilwang** [comment]
When no min_base_amount is returned, it means there is no limit on minimum base currency required. However, to create an order, you have to satisfy both base and quote minimum. In this case. Although no minimum amount is placed on ALEPH, the minimum quote amount is 1 USDT(which is also said in the error message), which means the value of your ALEPH order(amount * your order price) must be larger than 1 USDT.

**Comment by akashc-25** [comment]
What does the amount in this calculation (amount * your order price) represent—the minimum quotation amount, or the last price, or the amount=(minimum quote amount * total quantity)?

And correct me if I'm wrong, but does "your order price" in the formula equal to this formula (minimum quote amount * total quantity)?

**Comment by revilwang** [comment]
It means your order amount. That is, your order must meet the following requirements.

1. Order amount > min_base_amount
2. Order amount * Order price > min_quote_amount

When either min_quote_amount or min_base_amount is missing, just ignore corresponding requirement.

**Comment by akashc-25** [comment]
Okay, Thank you
