### ISSUE TITLE
auth faild , auth data : \u0026{{87260}

### ISSUE THREAD

**Issue by sunysen** [gateio/gateapi-python#14]
订阅futures.orders和futures.balances的websocket，都报如下错误，不知道什么意思
{"time":1570513208,"channel":"futures.orders","event":"subscribe","error":{"code":2,"message":"auth faild , auth data : \u0026{{87260}}"},"result":{"status":"failed"}}

**Comment by revilwang** [comment]
请提供以下信息：

1. 服务器连接地址
2. 使用的 API key 是模拟还是实盘
3. 请求体信息
4. 验签计算代码片段

**Comment by sunysen** [comment]
`api_key = 'xxxx'
secret_key = 'xxx'

ws = create_connection("wss://fx-ws.gateio.ws/v4/ws", http_proxy_host='127.0.0.1', http_proxy_port=1087)

current_time = int(time.time())
message = 'channel=%s&event=%s&time=%s' % ('futures.orders', 'subscribe', current_time)
print(message)
signature = hmac.new(bytes(secret_key, 'utf8'), bytes(message, encoding='utf8'), hashlib.sha512).hexdigest()
print(signature)
signature = hmac.new(bytes(secret_key, 'utf8'), message.encode("utf8"), hashlib.sha512).hexdigest()
print(signature)

subscribe = {
    "time": current_time,
    "channel": "futures.orders",
    "event": "subscribe",
    "payload": ["20011", "BTC_USD"],
    "auth": {
        "method": "api_key",
        "KEY": api_key,
        "SIGN": signature
    }}
# subscribe = {
#     "time": current_time,
#     "channel": "futures.balances",
#     "event": "subscribe",
#     "payload": ["20011"],
#     "auth": {
#         "method": "api_key",
#         "KEY": api_key,
#         "SIGN": signature
#     }}
ws.send(json.dumps(subscribe))
print(ws.recv())
`
使用是是实盘api

**Comment by revilwang** [comment]
请确保您在请求体里 payload 里传递的 user ID 与使用验签的用户 ID 保持一致

**Comment by revilwang** [comment]
未收到issue更新，该issue关闭，如果本问题未解决，请重开
