### ISSUE TITLE
order book quantities

### ISSUE THREAD

**Issue by gezabohus** [gateio/gateapi-python#152]
Hi,

From experimentation I found that order book quantities are in units of 0.01, meaning that if you see

1864.20  3549

in the ETH/USDT order book, it means that 35.49 ETH is offered. 

I don't see this written down anywhere and I'm not sure if it's the same for all currency pairs.

On the web interface the units are 1, so in this case you'd see

1864.20  35.49

Please help.

**Comment by revilwang** [comment]
Are you referring to perpetual futures order book? The latter one is not amount, but the size of contracts. For ETH/USDT, one contract has a value of 0.01 ETH(quanto_multiplier in contract detail), which is why you see 3549.

**Comment by gezabohus** [comment]
Got it, thank you.
