### ISSUE TITLE
深度数据咨询

### ISSUE THREAD

**Issue by sunysen** [gateio/gateapi-python#17]
[{'p': '3.097', 's': 0, 'c': 'EOS_USD', 'id': 24679122}, {'p': '3.078', 's': 981, 'c': 'EOS_USD', 'id': 24679123}]
[{'p': '3.082', 's': 0, 'c': 'EOS_USD', 'id': 24679264}, {'p': '3.088', 's': 516, 'c': 'EOS_USD', 'id': 24679265}]
[{'p': '3.099', 's': -78, 'c': 'EOS_USD', 'id': 24679124}, {'p': '3.11', 's': -779, 'c': 'EOS_USD', 'id': 24679125}]
1、深度更新的时候，0代表是卖盘还是买盘
2、更新的数据如何对于第几档位上

**Comment by revilwang** [comment]
更新的数据必须结合全量数据看，单纯看更新的数据没有意义

1. 档位在全量里才能体现
2. 0 代表之前数据里对应价格买卖都没有任何挂单（已全部成交）

**Comment by sunysen** [comment]
和全量数据对应呢，是通过价格价格对应吗

**Comment by sunysen** [comment]
或者你给我一个例子吗

**Comment by revilwang** [comment]
数据都是按照价格进行汇聚的，更新也是更新对应价格新的挂单数量

**Comment by sunysen** [comment]
好，我理解，那就是比对价格就可以对应了，非常感谢你回复
