### ISSUE TITLE
请问是否有所有api返回的错误列表

### ISSUE THREAD

**Issue by sunysen** [gateio/gateapi-python#18]
请问是否有所有api返回的错误列表

**Comment by revilwang** [comment]
http api的错误标识都会通过返回体里的 `label` 标识，合约相关的 label 列表如下，之后会更新到合约文档中：

请求参数或格式问题:

- INVALID_PARAM_VALUE: 参数输入值无效
- INVALID_PROTOCOL: 参数输入值无效
- INVALID_ARGUMENT: 参数输入值无效
- INVALID_REQUEST_BODY: 无效请求体
- MISSING_REQUIRED_PARAM: 缺少必选参数

认证相关:

- INVALID_CREDENTIALS: 认证接口缺少用户认证信息
- USER_NOT_FOUND: 用户无期货账户

业务相关:

- CONTRACT_NO_COUNTER: 没有匹配的对手单
- CONTRACT_NOT_FOUND: 合约未找到
- NOT_FOUND: 请求路径不存在
- RISK_LIMIT_EXCEEDED: 委托超出风险限额
- INSUFFICIENT_AVAILABLE: 余额不足
- LIQUIDATE_IMMEDIATELY: 操作可能导致爆仓
- LEVERAGE_TOO_HIGH: 杠杆倍数设置过高
- LEVERAGE_TOO_LOW: 杠杆倍数设置过低
- ORDER_NOT_FOUND: 委托不存在
- ORDER_NOT_OWNED: 委托不存在
- ORDER_FINISHED: 委托已结束
- TOO_MANY_ORDERS: 过多未完成的委托
- POSITION_CROSS_MARGIN: 全仓不支持更新保证金
- POSITION_IN_LIQUIDATION: 仓位在强制平仓中
- POSITION_IN_CLOSE: 仓位正在平仓中
- POSITION_EMPTY: 仓位为空
- REMOVE_TOO_MUCH: 保证金超过可调范围
- RISK_LIMIT_NOT_MULTIPLE: 风险限额未按照步长调整
- RISK_LIMIT_TOO_HIGH: 超出最大风险限额
- RISK_LIMIT_TOO_lOW: 风险限额设置过低
- PRICE_TOO_DEVIATED: 下单价与标记价格相差过大
- SIZE_TOO_LARGE: 下单数量超过上限
- SIZE_TOO_SMALL: 下单数量不足下限
- PRICE_OVER_LIQUIDATION: 增加仓位时价格不能超过平仓价
- PRICE_OVER_BANKRUPT: 减少仓位时价格不能超过破产价
- ORDER_POC_IMMEDIATE: 被动委托会立即成交
- INCREASE_POSITION: 只减仓委托会增加仓位

服务异常：
- INTERNAL: 内部错误
- SERVER_ERROR: 内部错误
- TOO_BUSY: 服务当前忙

**Comment by sunysen** [comment]
感谢感谢

**Comment by revilwang** [comment]
API文档新增了“异常处理”章节，完整错误列表移步：https://www.gateio.life/docs/apiv4/zh_CN/index.html#066247572d

"Error Handling" section is added into API documents. Refer to 
https://www.gate.io/docs/apiv4/en/index.html#066247572d
for details
