### ISSUE TITLE
合约的websocket如何保持心跳

### ISSUE THREAD

**Issue by sunysen** [gateio/gateapi-python#19]
我看文档说服务器主动发送ping，客户端没有响应会断开，我订阅几个接口并没有收到ping命令

**Comment by revilwang** [comment]
这个ping机制是WebSocket协议层的客户端存活探测，应用层感知不到，具体内容参考下方给出的 websocket rfc 文档里的定义

**Comment by revilwang** [comment]
具体章节参考 5.5.2 和 5.5.3

**Comment by sunysen** [comment]
那就是说应用层不需要关注吗

**Comment by revilwang** [comment]
是的，应用层不需要关心
