### ISSUE TITLE
how to use this api to trade with my margin funds

### ISSUE THREAD

**Issue by chendonghp** [gateio/gateapi-python#2]
The MarginApi don't provide the "create order" method, is there any way i can use to trade on margin.

I try this:
1. create an order
order=gate_api.Order(currency_pair='ATOM_USDT',price=4.82,account='margin',amount=1,side='sell')
spot = gate_api.SpotApi(gate_api.ApiClient(configuration))

2. then passing the order to spot.create_order
api_response=spot.create_order(order=order)

This method raises exception below: 
ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 03 May 2019 13:25:20 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '61', 'Connection': 'keep-alive', 'Server': 'openresty/1.13.6.1', 'X-Request-Id': '[1879f505]'})
HTTP response body: {"label":"BALANCE_NOT_ENOUGH","message":"balance not enough"}

**Comment by revilwang** [comment]
Make sure you have enough balance in your MARGIN account. Transferring from spot account to margin account currently is NOT supported with API - but it's on the way - you have to operate it on the web or mobile apps

**Comment by chendonghp** [comment]
I mean how to trade with my magin currency, I have transferred my usdt to margin account.

**Comment by revilwang** [comment]
That is the correct way to trade with margin account. Margin trading shares the same API with spot trading with one exception: fill the `account` with `margin`

**Comment by pumpthis** [comment]
v2的api 下单接口里填入参数 'account':'margin' 没有用啊 只有v4的下单接口才有杠杆交易吗？

**Comment by revilwang** [comment]
> v2的api 下单接口里填入参数 'account':'margin' 没有用啊 只有v4的下单接口才有杠杆交易吗？

是的，v2 的 API 不支持杠杆借贷和交易。v4 里杠杆和现货交易都是使用现货交易接口，注意区分 `account` 就可以

**Comment by pumpthis** [comment]
> > v2的api 下单接口里填入参数 'account':'margin' 没有用啊 只有v4的下单接口才有杠杆交易吗？
> 
> 是的，v2 的 API 不支持杠杆借贷和交易。v4 里杠杆和现货交易都是使用现货交易接口，注意区分 `account` 就可以

你好 我合约一直用v4跑的程序，今天拿v4的代码封装现货接口，同样的加密方法，api地址从'https://fx-api.gateio.ws'换成'https://api.gateio.ws'，别的封装方法一模一样，但是一直返回我{'label': 'INVALID_SIGNATURE', 'message': 'Signature mismatch'} 大概是什么原因呢？

**Comment by revilwang** [comment]
> > > v2的api 下单接口里填入参数 'account':'margin' 没有用啊 只有v4的下单接口才有杠杆交易吗？
> > 
> > 
> > 是的，v2 的 API 不支持杠杆借贷和交易。v4 里杠杆和现货交易都是使用现货交易接口，注意区分 `account` 就可以
> 
> 你好 我合约一直用v4跑的程序，今天拿v4的代码封装现货接口，同样的加密方法，api地址从'[https://fx-api.gateio.ws'换成'https://api.gateio.ws'，别的封装方法一模一样，但是一直返回我{'label](https://fx-api.gateio.ws'%E6%8D%A2%E6%88%90'https://api.gateio.ws'%EF%BC%8C%E5%88%AB%E7%9A%84%E5%B0%81%E8%A3%85%E6%96%B9%E6%B3%95%E4%B8%80%E6%A8%A1%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E4%B8%80%E7%9B%B4%E8%BF%94%E5%9B%9E%E6%88%91%7B'label)': 'INVALID_SIGNATURE', 'message': 'Signature mismatch'} 大概是什么原因呢？

合约有独立的 API key 和 secret，请在官网页面上 APIv4Keys 里对应位置获取。

如果是用 `gateapi-python` 的封装的话，使用方式如下：

```python
futures_cfg = gate_api.Configuration()
futures_cfg.key, futures_cfg.secret = 'FUTURES_API_KEY', 'FUTURE_API_SECRET'
futures_api = gate_api.FuturesApi(gate_api.ApiClient(futures_cfg)

# 使用 futures_api 进行合约接口调用

cfg = gate_api.Configuration()
cfg.key, cfg.secret = 'SPOT_API_KEY', 'SPOT_API_SECRET'
spot_api = gate_api.SpotApi(gate_api.ApiClient(cfg))
margin_api = gate_api.MarginApi(gate_api.ApiClient(cfg))

# 使用 spot_api 进行现货交易，margin_api 进行杠杆借贷操作
```

**Comment by chendonghp** [comment]
> That is the correct way to trade with margin account. Margin trading shares the same API with spot trading with one exception: fill the `account` with `margin`

I list my margin accounts:
![image](https://user-images.githubusercontent.com/11484896/57272510-978dd100-70c6-11e9-8049-b5dcd9ba8433.png)
I want to trade ATOM, but the return results have no ATOM available.
But in APP, I do have some ATOM:
![InkedWeChat Image_20190507125347_LI](https://user-images.githubusercontent.com/11484896/57272747-8d200700-70c7-11e9-979b-91c3d60b9f52.jpg)

I alse tried this:
margin.list_margin_accounts()
![image](https://user-images.githubusercontent.com/11484896/57272827-d83a1a00-70c7-11e9-8ab3-dc33f53f0dd2.png)

**Comment by revilwang** [comment]
Issue closed because of too much off-topic discussions. For other questions, create new issue or contact the official support.

**Comment by pumpthis** [comment]
> > > > v2的api 下单接口里填入参数 'account':'margin' 没有用啊 只有v4的下单接口才有杠杆交易吗？
> > > 
> > > 
> > > 是的，v2 的 API 不支持杠杆借贷和交易。v4 里杠杆和现货交易都是使用现货交易接口，注意区分 `account` 就可以
> > 
> > 
> > 你好 我合约一直用v4跑的程序，今天拿v4的代码封装现货接口，同样的加密方法，api地址从'[https://fx-api.gateio.ws'换成'https://api.gateio.ws'，别的封装方法一模一样，但是一直返回我{'label](https://fx-api.gateio.ws'%E6%8D%A2%E6%88%90'https://api.gateio.ws'%EF%BC%8C%E5%88%AB%E7%9A%84%E5%B0%81%E8%A3%85%E6%96%B9%E6%B3%95%E4%B8%80%E6%A8%A1%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E4%B8%80%E7%9B%B4%E8%BF%94%E5%9B%9E%E6%88%91%7B'label)': 'INVALID_SIGNATURE', 'message': 'Signature mismatch'} 大概是什么原因呢？
> 
> 合约有独立的 API key 和 secret，请在官网页面上 APIv4Keys 里对应位置获取。
> 
> 如果是用 `gateapi-python` 的封装的话，使用方式如下：
> 
> ```python
> futures_cfg = gate_api.Configuration()
> futures_cfg.key, futures_cfg.secret = 'FUTURES_API_KEY', 'FUTURE_API_SECRET'
> futures_api = gate_api.FuturesApi(gate_api.ApiClient(futures_cfg)
> 
> # 使用 futures_api 进行合约接口调用
> 
> cfg = gate_api.Configuration()
> cfg.key, cfg.secret = 'SPOT_API_KEY', 'SPOT_API_SECRET'
> spot_api = gate_api.SpotApi(gate_api.ApiClient(cfg))
> margin_api = gate_api.MarginApi(gate_api.ApiClient(cfg))
> 
> # 使用 spot_api 进行现货交易，margin_api 进行杠杆借贷操作
> ```

已解决 加密的时候url没填上/api/v4这一段字符 填上后就对了
