### ISSUE TITLE
u本位合约api测试地址有么

### ISSUE THREAD

**Issue by Jastyle** [gateio/gateapi-python#20]
请问u本位合约的api测试地址有么，我用https://fx-api-testnet.gateio.ws/api/v4这个测试地址获取仓位，报{"label":"CONTRACT_NOT_FOUND"}错误，币本位正常。

**Comment by revilwang** [comment]
请提供具体的代码

**Comment by Jastyle** [comment]
configuration.host = "https://fx-api-testnet.gateio.ws/api/v4"
GateSwapApi = gate_api.FuturesApi(gate_api.ApiClient(configuration))
CONTRACT = 'BTC_USD'
BTC_SETTLE = 'btc'
USDT_SETTLE = 'usdt'

if __name__ == '__main__':
    position = GateSwapApi.get_position(settle=USDT_SETTLE, contract=CONTRACT)
    print(position)

**Comment by revilwang** [comment]
你应该是把 contract 的名字写错了，可以通过 `list_futures_contracts` 查询到所有支持的列表

```python
supported = [x.name for x in GateSwapApi.list_futures_contracts(settle=USDT_SETTLE)]
```

**Comment by Jastyle** [comment]
￣□￣｜｜，谢谢！
