### ISSUE TITLE
请问是否有查询平台所有强平订单的接口

### ISSUE THREAD

**Issue by sunysen** [gateio/gateapi-python#21]

**Comment by revilwang** [comment]
https://www.gate.io/docs/apiv4/zh_CN/index.html#84cd66b30d

**Comment by revilwang** [comment]
国内用户可以访问 https://www.gateio.life/docs/apiv4/zh_CN/index.html#84cd66b30d

**Comment by sunysen** [comment]
这个api是查询个人的强平历史吗？还是说平台全部强平历史

**Comment by revilwang** [comment]
需要认证的接口，是个人的
