### ISSUE TITLE
查询个人强平订单，还是平台所有平仓订单

### ISSUE THREAD

**Issue by sunysen** [gateio/gateapi-python#22]
是查询个人强平订单，还是平台所有平仓订单

**Comment by sunysen** [comment]
https://www.gateio.life/docs/apiv4/zh_CN/index.html#84cd66b30d

**Comment by revilwang** [comment]
个人的，平台的暂未提供

**Comment by revilwang** [comment]
您是需要什么样的全平台的平仓记录数据？有什么具体的使用场景吗？

**Comment by sunysen** [comment]
做统计用，类似火币curl "https://api.hbdm.com/api/v1/contract_liquidation_orders?symbol=BTC&trade_type=0&create_date=7"
这个接口，最好是websoket实时推送

**Comment by revilwang** [comment]
新增永续合约的强平历史查询 https://www.gateio.pro/docs/apiv4/zh_CN/index.html#e6057f86d4
