### ISSUE TITLE
关于sdk的问题

### ISSUE THREAD

**Issue by cjrey-good** [gateio/gateapi-python#23]
想问一下。
Gate API v4 v4.11.0中提供的python sdk 和 网页版API是一样的吗？
api版本更新，网页版的和sdk都是同步更新吗？
访问端口，反馈速度等都是没差别的吗。

**Comment by revilwang** [comment]
完全一致的，因为是基于 OpenAPI 标准书写的 API，所以每次文档跟SDK都是自动生成的，能保持高度同步更新

**Comment by cjrey-good** [comment]
> 完全一致的，因为是基于 OpenAPI 标准书写的 API，所以每次文档跟SDK都是自动生成的，能保持高度同步更新

明白，谢谢。
