### ISSUE TITLE
关于k线数据获取api

### ISSUE THREAD

**Issue by cjrey-good** [gateio/gateapi-python#24]
/spot/candlesticks
这个api如果设置1d，则返回的开盘价是24小时前开盘价，还是上午8点（当日）开盘价？
是否有时区区分？

**Comment by revilwang** [comment]
无时区区分，统一按0时区来统计的

**Comment by cjrey-good** [comment]
> 无时区区分，统一按0时区来统计的

这个api的开盘价是北京时间早上8点的价格吗？

**Comment by revilwang** [comment]
是的，0时区的0点对应到北京时间的8点

**Comment by cjrey-good** [comment]
好的 谢谢
再问一个问题。
如果我想批量获取K线数据，比如一万条数据，这个api好像会服务器超时报错。
是否有别的办法和途径来获取呢？

**Comment by cjrey-good** [comment]
> 是的，0时区的0点对应到北京时间的8点

好的 谢谢
再问一个问题。
如果我想批量获取K线数据，比如一万条数据，这个api好像会服务器超时报错。
是否有别的办法和途径来获取呢？

**Comment by revilwang** [comment]
设置1万条数据不是返回正常应该会返回超过上限要求的，我跟进下超时的问题

目前还不行，考虑通过from 和 to来传入需要的时间范围来获取历史数据，因为单次获取的量还是要控制下的

**Comment by revilwang** [comment]
> 设置1万条数据不是返回正常应该会返回超过上限要求的，我跟进下超时的问题
> 

经测试如果 `limit` 设置超过1000以上的数据时，的确是会返回参数无效的问题，不知道你说的接口会返回超时，具体是什么样的一个请求参数？

**Comment by cjrey-good** [comment]
> > 设置1万条数据不是返回正常应该会返回超过上限要求的，我跟进下超时的问题
> 
> 经测试如果 `limit` 设置超过1000以上的数据时，的确是会返回参数无效的问题，不知道你说的接口会返回超时，具体是什么样的一个请求参数？

k线API里，直接请求10000条数据，不会出现参数无效的异常，而是等到后面超时。

**Comment by revilwang** [comment]
如果直接访问这个地址 https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=BTC_USDT&limit=10000 会返回

```json
{"label":"INVALID_PARAM_VALUE","message":"Invalid request parameter `limit` value: 10000"}
```

请求10000条数据会出现超时的具体请求参数是什么？

**Comment by cjrey-good** [comment]
> 如果直接访问这个地址 https://api.gateio.ws/api/v4/spot/candlesticks?currency_pair=BTC_USDT&limit=10000 会返回
> 
> ```json
> {"label":"INVALID_PARAM_VALUE","message":"Invalid request parameter `limit` value: 10000"}
> ```
> 
> 请求10000条数据会出现超时的具体请求参数是什么？

设置和你的一样  可能是我这边网络问题  我打开你的链接也是无效数据
另外，这边K线数据正常请求时，间歇性INVALID_PARAM_VALUE返回，不知道是什么原因

[20200410_Error_log.zip](https://github.com/gateio/gateapi-python/files/4460034/20200410_Error_log.zip)

**Comment by revilwang** [comment]
出现 INVALID_PARAM_VALUE 的时候，message 里的内容是什么？

**Comment by revilwang** [comment]
`/spot/candlesticks` 已支持指定 `from` 和 `to` 的时间范围来获取历史数据，具体使用说明参考 https://www.gate.io/docs/apiv4/zh_CN/index.html#k
