### ISSUE TITLE
关于SERVER_ERROR异常以及间歇性INVALID_PARAM_VALUE异常

### ISSUE THREAD

**Issue by cjrey-good** [gateio/gateapi-python#25]
今天从上午9点到下午6点进行了代码测试，gate服务器会返回如题异常。
INVALID_PARAM_VALUE是间歇性的，SERVER_ERROR从5点47开始发生。
麻烦看一下是什么问题呢？
[20200407_Error_log.pdf](https://github.com/gateio/gateapi-python/files/4443712/20200407_Error_log.pdf)

**Comment by revilwang** [comment]
感谢提交日志，我这边逐条确认下

**Comment by revilwang** [comment]
建议检查返回的 http status code，如果是 4xx 之类的错误，还是跟具体的请求参数有关系，可以通过打印body里的message来确认是具体什么参数引起的错误。诸如 INVALID_PARAM_VALUE 就是一个典型的 400 错误

SERVER_ERROR的问题我这边再确认下

**Comment by revilwang** [comment]
SERVER_ERROR是由于系统升级导致了一段时间不可用

**Comment by cjrey-good** [comment]
> SERVER_ERROR是由于系统升级导致了一段时间不可用

好的谢谢  我这边也改善一下代码
