### ISSUE TITLE
合约API收到401错误 Missing required header: Timestamp

### ISSUE THREAD

**Issue by cqtenq** [gateio/gateapi-python#26]
之前已经调试通过的Python代码，最近执行遇到API报错：
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Sat, 11 Apr 2020 16:17:12 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty'})
HTTP response body: {"label":"MISSING_REQUIRED_HEADER","message":"Missing required header: Timestamp"}
已经更新Python版本的API代码4.11版本，咨询一下如何解决。

**Comment by revilwang** [comment]
用的是Python SDK ？请提供具体代码片段

**Comment by revilwang** [comment]
长时间无响应，关闭该 issue
