### ISSUE TITLE
api网页无法打开

### ISSUE THREAD

**Issue by cjrey-good** [gateio/gateapi-python#27]
https://www.gateio.life/docs/apiv4/zh_CN/index.html#gate-api-v4
这个api地址无法打开，是服务器原因？
另外，官网的提供的api地址（https://www.gatecn.io/api2#spot）为什么是旧的呢？
git上是否有电子版（实时更新）？

**Comment by revilwang** [comment]
你好，
https://www.gatecn.io/api2#spot 是 APIv2的文档

https://www.gateio.life/docs/apiv4/zh_CN/index.html#gate-api-v4 是 API4 的文档，关于两者区别可以参考 https://www.gateio.life/docs/apiv4/zh_CN/index.html#apiv2

经测试 https://www.gateio.life/docs/apiv4/zh_CN/index.html 是可以打开的，域名换成 gatecn.io 是否能打开？
另外这个链接里的文档会始终保持与实现同步更新，所以不用担心不实时的问题

**Comment by cjrey-good** [comment]
> 你好，
> https://www.gatecn.io/api2#spot 是 APIv2的文档
> 
> https://www.gateio.life/docs/apiv4/zh_CN/index.html#gate-api-v4 是 API4 的文档，关于两者区别可以参考 https://www.gateio.life/docs/apiv4/zh_CN/index.html#apiv2
> 
> 经测试 https://www.gateio.life/docs/apiv4/zh_CN/index.html 是可以打开的，域名换成 gatecn.io 是否能打开？
> 另外这个链接里的文档会始终保持与实现同步更新，所以不用担心不实时的问题

你好
域名更换后可以登陆了。谢谢。
