### ISSUE TITLE
POST /spot/orders 中的type参数

### ISSUE THREAD

**Issue by cjrey-good** [gateio/gateapi-python#28]
如题。api说明中，仅提供了limit一个说明，没有别的type值了吗？
如我想以固定价格买入而非当前价交易，该如何输入？

**Comment by revilwang** [comment]
这个接口目前只支持固定价格，设置 price 字段为需要的价格

**Comment by cjrey-good** [comment]
> 这个接口目前只支持固定价格，设置 price 字段为需要的价格

那为什么我输入eh usdt 250价格买去 它仍然已当前成交价成交了呢？

**Comment by revilwang** [comment]
price是设置的期望价格，实际成交价会按照更利于发起人的价格来成交，比如以250买入，但是市场有249卖，则会以249的价格成交。

**Comment by cjrey-good** [comment]
> price是设置的期望价格，实际成交价会按照更利于发起人的价格来成交，比如以250买入，但是市场有249卖，则会以249的价格成交。

好的 明白  谢谢
