### ISSUE TITLE
保证金接口 {'message': 'Internal server error', 'label': 'SERVER_ERROR'}

### ISSUE THREAD

**Issue by pumpthis** [gateio/gateapi-python#3]
我有两个账号 api请求其中一个账号全部正常 请求另一个账号的spot api也没问题 但是请求margin api时，返回{'message': 'Internal server error', 'label': 'SERVER_ERROR'}
uid是2541076

**Comment by pumpthis** [comment]
包括margin下单 margin账户查询都返回Internal server error    刷新系统lv4 api 用了新的api和secret也没用

**Comment by pumpthis** [comment]
@revilwang

**Comment by revilwang** [comment]
稍等，在处理中

**Comment by revilwang** [comment]
> 我有两个账号 api请求其中一个账号全部正常 请求另一个账号的spot api也没问题 但是请求margin api时，返回{'message': 'Internal server error', 'label': 'SERVER_ERROR'}
> uid是2541076

账户查询的问题已经处理

**Comment by pumpthis** [comment]
api请求已成功 谢谢
