### ISSUE TITLE
怎么创建USDT结算价格追踪订单

### ISSUE THREAD

**Issue by solmyr117** [gateio/gateapi-python#30]
用这个接口创建订单时，
https://github.com/gateio/gateapi-python/blob/master/docs/FuturesApi.md#create_price_triggered_order
没找么怎么创建USDT结算的，BTC结算的可以创建

**Comment by revilwang** [comment]
把 settle 设置成 `usdt` 就可以了

**Comment by solmyr117** [comment]
把 settle 设置成 usdt 返回没有这个交易对？

**Comment by solmyr117** [comment]
不好意思，是我搞错了。。可以了
