### ISSUE TITLE
永续合约下单有实例吗？

### ISSUE THREAD

**Issue by yazhoushi** [gateio/gateapi-python#31]
我没有下单成功过！不知道什么原因？可以给个永续合约下单的实例吗？谢谢了

**Comment by revilwang** [comment]
更完整的示例已经在准备中了，先问一下具体遇到的问题是什么？

**Comment by yazhoushi** [comment]
报400错误！Exception when calling FuturesApi->create_futures_order: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 13 Aug 2020 01:40:17 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty'})
HTTP response body: {"label":"INVALID_PROTOCOL","detail":"invalid argument: #3"}

**Comment by yazhoushi** [comment]
@revilwang 
api_instance = gate_api.FuturesApi(gate_api.ApiClient(configuration))
settle = 'usdt' # str | Settle currency (default to 'btc')
contract = 'FIL_USDT'  # 合约标识
tif ='gtc'

futures_order = gate_api.FuturesOrder(contract=contract, size=0.1,iceberg=0,price='21',tif=tif,text='t-my-custom')
# futures_order ='{"contract":"FIL_USDT","size":-0.1,"iceberg":0,"price":"21","tif":"gtc","text":"t-my-custom-id"}'
# {'contract': 'FIL_USDT', 'size': -0.1, 'iceberg': 0, 'price': '21', 'close': False, 'reduce_only': False, 'tif': 'gtc', 'text': 't-my-custom'}

try:
    # Create a futures order
    api_response = api_instance.create_futures_order(settle, futures_order)
    print(api_response)
except ApiException as e:
    print("Exception when calling FuturesApi->create_futures_order: %s\n" % e)      代码是这样的

**Comment by revilwang** [comment]
[FuturesOrder.md](https://github.com/gateio/gateapi-python/blob/master/docs/FuturesOrder.md) 里已经说明 size 是 int 类型，只能传整数。新版的 python SDK 增加了类型提示，如果你使用 PyCharm 之类的 IDE 应该会告诉你 size 字段格式不对

**Comment by yazhoushi** [comment]
@revilwang 好的！谢谢，可以了！

**Comment by revilwang** [comment]
API 调用示例已添加 

https://github.com/gateio/gateapi-python/tree/master/example

**Comment by yazhoushi** [comment]
我程序都跑了2个星期了

**Comment by revilwang** [comment]
哈哈哈，抱歉久等，因为有其他 SDK 的也要同步准备

**Comment by yazhoushi** [comment]
老板！有没有一些好的策略啊！求分享！你看bitmax上还开源了一个做市的策略！
