### ISSUE TITLE
请求延迟是多长时间？

### ISSUE THREAD

**Issue by yazhoushi** [gateio/gateapi-python#33]
我看了一下rest模块下面的request函数的_request_timeout参数的None！是这个_request_timeout参数设置post和get等等返回的延迟时间吗？我写了个脚本，然后直接死了哪里，try也没有错误出来，肯定是没有超时设置时间吗？

**Comment by revilwang** [comment]
如果你仔细看一下 rest.py 里的 docstring，会发现 _request_timeout 这个参数的格式说明：

```python
    def request(...):
        """
        ...
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        """
```

不提供则是按照默认的 urllib 标准库的超时设置。

如果你需要设置超时，`_request_time` 可以接受类似于 `requests` 库的时间格式：单一值，或者一个分别设置连接和读超时的 2 元 tuple，比如

```python
# 将连接超时和读超时都设置为 3s
api.get_currency_pair('BTC_USDT', _request_timeout=3)
# 设置连接超时为 3s，读超时设置为 5s
api.get_currency_pair('BTC_USDT', _request_timeout=(3, 5))
```

**Comment by yazhoushi** [comment]
谢谢啊！我去试试！使用说明对于我这种小白还是很重要的！感觉你们文档做得没有ccxt全面！合约挂单数量不能超过50个，我在任何的官方文档没有发现！同样的脚本放在云上，ccxt的请求和返回的速度比官方的速度快好多！这个是不是和底层的urllib3库有关系？

**Comment by yazhoushi** [comment]
官方的api接口还是很强大的，也许是我没有明白原理吧

**Comment by revilwang** [comment]
> 谢谢啊！我去试试！使用说明对于我这种小白还是很重要的！感觉你们文档做得没有ccxt全面！合约挂单数量不能超过50个，我在任何的官方文档没有发现！同样的脚本放在云上，ccxt的请求和返回的速度比官方的速度快好多！这个是不是和底层的urllib3库有关系？

1. 合约挂单数量不能超过 50 个的文档说明，在 Contract 的模型定义里有，最近发现少了这个字段的说明，下次文档更新会补上
2. 你说的速度快很多，能给一个大概的量级给我们评估下吗？响应速率很大概率是跟网络连通有关系，不知道你用的是哪个云？在云的哪个区域？

**Comment by revilwang** [comment]
> 官方的api接口还是很强大的，也许是我没有明白原理吧

近期在准备更加完整的 SDK 使用示例，争取在下个版本发布的时候带上，到时还请关注一下

**Comment by yazhoushi** [comment]
腾讯云在广东地区的！ccxt请求一次(请求加返回)api大概是稳定在0.03-0.15秒左右！用gateapi请求一次请求加返回大概是0.07--10秒不等，大部分都在0.1左右！

**Comment by yazhoushi** [comment]
现在的速度比之前的老的V2版本的rest快很多了

**Comment by yazhoushi** [comment]
ccxt也是开源的项目，你们看一下他们的底层请求链接的代码！应该对你有帮助吧

**Comment by revilwang** [comment]
这个数据都是针对现货的吗？cctx 目前只支持 gate api 2 ，也就是只有现货的接口

**Comment by yazhoushi** [comment]
是的

**Comment by revilwang** [comment]
好的，非常感谢你这边的信息。

另外如果你有多个请求并行操作，建议看一下 SDK 里的 `async_req` 参数，它可以将发送的请求异步化，减少 io 等待

**Comment by yazhoushi** [comment]
我用了线程池！多个线程请求，但是一个线程超时没有返回值也不能取消这个线程，后期程序还是会返回这个线程的值！我没有找到好的解决办法！我不知道你们这个异步怎么用？我用asyncio这个官方的库来异步的

**Comment by yazhoushi** [comment]
而且你们的异步可以解决，请求超时过后取消这个超时的task，防止try过后程序循环下一次操作，之前的task又返回值了导致程序取的值不是最新的数据！

**Comment by revilwang** [comment]
嗯，感谢建议。这个版本的 SDK 为了考虑做 Python 2.7 的兼容，所以没有使用 asyncio ，后续我们有时间或许会另开一个只支持 Python 3 并且利用 asyncio 的版本
