### ISSUE TITLE
现货划转杠杆账户交易对有方法吗？

### ISSUE THREAD

**Issue by yazhoushi** [gateio/gateapi-python#36]
有api接口函数吗？

**Comment by revilwang** [comment]
接口文档：

https://github.com/gateio/gateapi-python/blob/master/docs/WalletApi.md#transfer

示例代码：

https://github.com/gateio/gateapi-python/blob/master/example/margin.py#L71

注意调用该接口前，需要确保你使用的密钥对开启了 wallet 钱包的读写权限

**Comment by yazhoushi** [comment]
好的，谢谢
