### ISSUE TITLE
获取个人已经成交的订单

### ISSUE THREAD

**Issue by yazhoushi** [gateio/gateapi-python#37]
获取个人已经成交的订单（现货，合约，期货），能不能接口加一个字段text也跟着返回?（就是下单时候的字段text）

**Comment by revilwang** [comment]
查询 /orders 的时候会返回 `text` 字段

**Comment by yazhoushi** [comment]
get_my_trades(),是这个，获取个人历史成交纪录！

**Comment by revilwang** [comment]
`text` 字段是 `Order` 的一个属性，`get_my_trades` 会返回 `Order` 的 ID ，可以将创建订单时返回的  order id 与 text 做个映射关系，这样获取到的成交记录就能通过 `order_id` 跟 `text` 对应上了

**Comment by yazhoushi** [comment]
那不是多调用一次api！速度跟不上啊

**Comment by revilwang** [comment]
不会，下单时的返回，本身就已经带上了 order 的 id 和 text，本地做一个缓存映射就可以，不需要额外的网络消耗

**Comment by yazhoushi** [comment]
喔喔。。可以的！谢谢了

**Comment by yazhoushi** [comment]
不对啊！个人成交历史返回的ID和订单id根本对应不起来吧！2个id没有关联的吧

**Comment by revilwang** [comment]
个人成交里的 id 是成交记录 id，对应的 order id 是 `order_id` 字段， Trade.order_id = Order.id

**Comment by yazhoushi** [comment]
好的！我去观察一下！谢谢
