### ISSUE TITLE
websocket的接口库能不能重写一下啊！

### ISSUE THREAD

**Issue by yazhoushi** [gateio/gateapi-python#41]
3大所的websocket接口库都有！你只要把火币和币安的库看一下！然后套一下就可以发布了吧！比现在这个12个月都不更新的好多了！期待。。。。

**Comment by walter211** [comment]
3 months later

**Comment by Gwokshing** [comment]
> 3大所的websocket接口库都有！你只要把火币和币安的库看一下！然后套一下就可以发布了吧！比现在这个12个月都不更新的好多了！期待。。。。

哈哈哈哈哈哈哈哈哈

**Comment by yazhoushi** [comment]
> > 3大所的websocket接口库都有！你只要把火币和币安的库看一下！然后套一下就可以可以发布了吧！比现在这个12个月都不更新的好多了！期待。。。。
> 
> 哈哈哈哈哈哈哈哈哈哈

呵呵呵呵呵呵呵呵呵

**Comment by revilwang** [comment]
最近在优化 WebSocket 后端，待这些工作完成之后会介入到新的 WebSocket 客户端。

另外该仓库与 WebSocket 无关，相关需求我调整到对应仓库，该 issue 关闭 

新 issue 移步 gateio/WebSocket-API#12
