### ISSUE TITLE
Full Futures Position Close History

### ISSUE THREAD

**Issue by dextervip** [gateio/gateapi-python#43]
Hello,

Is there any way to get a full paginated list of closed position history? I am using futures list position close history method however it has a limit of 100 entries, I couldn't find any kind of pagination.

Regards

**Comment by revilwang** [comment]
This API provides only the latest 100 at most for now. I'll report back the issue to API implementation

**Comment by dextervip** [comment]
@revilwang, thank you! Also I am not sure If is this possible but adding the final balance amount on every close position would be helpfull. Like bybit and bitmex API, so that we can track the exact performance at that moment for investment return methods such as TWR.

**Comment by revilwang** [comment]
OK, this one will also be added. I'll leave this issue open until the request is fulfilled.

**Comment by revilwang** [comment]
One more thing, could you please provide the detailed bybit and bitmex API link?

**Comment by dextervip** [comment]
@revilwang Sure, here go:
https://bybit-exchange.github.io/docs/inverse/#t-walletrecords
https://github.com/BitMEX/api-connectors/blob/master/auto-generated/python/docs/UserApi.md#user_get_wallet_history

Actually, they return it as wallet history which includes closed positions, transfers in/out, and others. I haven't seen a similar method here or Am I wrong?

**Comment by revilwang** [comment]
I think this API will help you: https://github.com/gateio/gateapi-python/blob/master/docs/FuturesApi.md#list_futures_account_book

It returns the history of you futures account change. `type` field denotes how it is changed.

**Comment by dextervip** [comment]
@revilwang Oh, It looks like to solve my issue. I will take a look, thanks!

**Comment by revilwang** [comment]
A new field `offset` has been added. https://github.com/gateio/gateapi-python/blob/master/docs/FuturesApi.md#list_position_close

You can now use [limit-offset](http://gateio.pro/docs/apiv4/en/index.html#pagination) way to retrieve older position close history

**Comment by dextervip** [comment]
@revilwang that's great! About the account book list, what's the default sorting for no params? Looks like it starts from the recent entries. Am I correct?

**Comment by revilwang** [comment]
Yes. Sortings are all recent first

**Comment by dextervip** [comment]
@revilwang thank you. It's all good. I think this issue is solved, it may be closed.
