### ISSUE TITLE
How to place a market order?

### ISSUE THREAD

**Issue by discosultan** [gateio/gateapi-python#47]
This question is not about the Python API per se but the REST API in general.

Following the docs at [https://www.gate.io/docs/apiv4/en/index.html#create-an-order](https://www.gate.io/docs/apiv4/en/index.html#create-an-order), only `"type": "limit"` is a valid value. Can it also be used to place a market order? Intuitively, for a market order, I would set `"time_in_force": "ioc"`, but I don't know what to set the price.

I could query the orderbook for current prices and pick a price that would immediately fill, but perhaps there is an easier way?

**Comment by revilwang** [comment]
Market type order are not open yet, and it's not planned to. I would suggest subscribing to `spot.trade` to get the recent price or `spot.book_ticker` to get the best order book ask and bid price in realtime.

**Comment by discosultan** [comment]
Thanks for the clarification!
