### ISSUE TITLE
[Question] How to list main spot account balances?

### ISSUE THREAD

**Issue by discosultan** [gateio/gateapi-python#48]
From the API, I found the following method for listing sub-account balances: https://github.com/gateio/gateapi-python/blob/b559a15386b412d815fe3808a3e6c04e337952ee/gate_api/api/wallet_api.py#L853. I am not using sub-accounts and it returns an empty list for me.

I also tried the websocket API described here: https://www.gate.io/docs/apiv4/ws/index.html#client-subscription-9. This one only seems to deliver updates to balances, but cannot provide current snapshot of all balances.

How to list balances for main spot account? Should I use v2 REST API instead?

**Comment by revilwang** [comment]
Use this one https://github.com/gateio/gateapi-python/blob/master/docs/SpotApi.md#list_spot_accounts

**Comment by discosultan** [comment]
Thanks @revilwang, totally missed this one!

**Comment by acairon** [comment]
its possible to get all in one query? or i need to changue currency variable?

**Comment by revilwang** [comment]
Currency is optional. Omitting it returns all currencies

**Comment by acairon** [comment]
whit this https://github.com/gateio/gateapi-python/blob/master/docs/SpotApi.md#list_spot_accounts give me empty list , or only returns that i have

**Comment by revilwang** [comment]
Currencies that you have deposited
