### ISSUE TITLE
超时time怎么设置

### ISSUE THREAD

**Issue by qs-lll** [gateio/gateapi-python#49]
环境:python
问题:由于默认timeout时间太长 导致拉不到数据容易卡死,怎么设置timeout在python api里

**Comment by revilwang** [comment]
目前还没有一个全局的超时配置，但是每个接口可以额外传入一个 `_request_timeout` 来设置超时时间，格式与 `requests` 的超时一样，支持单个 int 或者一个二元 tuple ，比如

```python
spot_api.get_currency('BTC', _request_timeout=(3,10))
```
