### ISSUE TITLE
个别杠杆账户出现无法下单的情况

### ISSUE THREAD

**Issue by pumpthis** [gateio/gateapi-python#5]
你好 我的uid是2541076 我在七个币种上做杠杆下单，六个币种完全正常，但是xrp币种有个问题。

xrp杠杆账户余额是一万个xrp，网页版杠杆页面可以挂一万xrp的卖单并撤掉，但是通过api挂3000个xrp的卖单，显示 {'label': 'MARGIN_BALANCE_NOT_ENOUGH', 'message': 'No margin account or margin balance is not enough'}
这个是个别币种的现象，不是普遍的。

**Comment by pumpthis** [comment]
@revilwang

**Comment by revilwang** [comment]
如果出现类似的错误，可以通过 list_margin_acounts 返回的指定币种的 available 是不是足够

**Comment by pumpthis** [comment]
你好 我的uid是2541076 今天重新在xrp杠杆账户中下单 重现了这个问题


网页界面显示账户里余额5500个xrp

api 请求杠杆余额 返回 {'base': {'locked': '0', 'borrowed': '7500', 'currency': 'XRP', 'available': '5526.0604'}, 'quote': {'locked': '0', 'borrowed': '0', 'currency': 'USDT', 'available': '2123.9421332'}, 'currency_pair': 'XRP_USDT'}

然后我通过现货api下单杠杆
/api/v4/spot/orders {'amount': '3000', 'side': 'sell', 'account': 'margin', 'price': '0.4', 'currency_pair': 'xrp_usdt'} {'Content-Type': 'application/json', 'Accept': 'application/json', 'Timestamp': '1557459912.537898', 'KEY': XXX, 'SIGN': XXX}

返回了{'label': 'MARGIN_BALANCE_NOT_ENOUGH', 'message': 'No margin account or margin balance is not enough'}

**Comment by pumpthis** [comment]
我的trx杠杆账户也出现了这个问题，别的币种btc ltc eth等等全都正常

**Comment by pumpthis** [comment]
目前xrp账户下单一直是这个状态 我的xrp杠杆账户保持不交易 可以一直重现这个问题。

**Comment by pumpthis** [comment]
@revilwang

**Comment by revilwang** [comment]
稍等，帮您确认下问题

**Comment by revilwang** [comment]
@pumpthis XRP_USDT 问题已经处理

**Comment by pumpthis** [comment]
收到 程序的单子全部挂上去了。
 感谢！
