### ISSUE TITLE
Rebasing info

### ISSUE THREAD

**Issue by Kalindro** [gateio/gateapi-python#50]
Hello! Is there any part where API endpoints inform about currency "rebasing"? (whatever it is)? trade_status in list_currency_pairs() gives "tradable" status even tho I wouldn't call it tradable as not all actions can be taken on the pair then.

**Comment by revilwang** [comment]
Rebasing status currently is not returned, but there is an aggressive way to check if currency is rebasing. You can just placing new orders and check `GateApiException` like this:

```python
try:
    created = spot_api.create_order(order)
except GateApiException as e:
    if e.label in ('REBASING', 'INVALID_CURRENCY', 'INVALID_CURRENCY_PAIR'):
        print('rebasing")
```

**Comment by Kalindro** [comment]
Thanks @revilwang, having an exception for it also works!
