### ISSUE TITLE
Scientific notation price

### ISSUE THREAD

**Issue by Kalindro** [gateio/gateapi-python#51]
Hello, I have encountered a weird thing. Why can't I pass price as scientific notation? It's not a case for all other exchanges, I get an "Invalid requests parameter 'price' value: 6.521e-05" (here is an example for HSC/USDT) error, how is it possible that endpoint doesn't accept scientific notation? Making it a string doesn't help. How can I solve that?

**Comment by revilwang** [comment]
The server does not parse any scientific notations. One way you can do is using `decimal.Decimal` to wrap your price or amount. Then using `format(your_decimal_object, 'f')`

**Comment by Kalindro** [comment]
Thanks, I will try that!
