### ISSUE TITLE
现货有时候没有卖出去

### ISSUE THREAD

**Issue by loserZhang** [gateio/gateapi-python#52]
利用现货接口出售时，有时候没有完全卖出去，是不是因为按当前价格挂单只交易成功了一部分，之后价格降低交易不出去，从而自动取消了订单？

**Comment by revilwang** [comment]
会存在只成交部分的情况，并且如果 tif 指定的是 ioc ，系统会自动取消未完全成交的单子。如果不是 ioc ，系统不会主动撤销未完全成交订单

**Comment by loserZhang** [comment]
请问对于这种情况有啥方法可以解决么，即未成交的部分订单继续挂价知道完全成交

**Comment by loserZhang** [comment]
请问对于这种情况有啥方法可以解决么，即未成交的部分订单继续挂价直到完全成交

**Comment by revilwang** [comment]
tif 默认值是 gtc ，这种情况就是未成交的部分会持续挂单直到完全成交或者被用户主动撤销为止。

你的意思是未设置 tif 的情况时出现未成交部分被系统主动撤销的情况？

**Comment by loserZhang** [comment]
默认gtc的情况下，会自动持续挂单直到完全成交是吧，每次按最新价格持续挂单么

**Comment by revilwang** [comment]
按创建订单时提交的价格持续挂单

**Comment by loserZhang** [comment]
那要是下降趋势，岂不是会一直成交不了？

**Comment by revilwang** [comment]
是的，所以需要用户自己自行决定是否及时撤销同时以新的价格挂单，系统不会更改用户下单的价格

**Comment by loserZhang** [comment]
好的，谢谢，请问这个在代码里面有样例么

**Comment by revilwang** [comment]
没有，这种行为属于用户自行决定的一些策略。不过撤单等每个单独的接口使用我们是有提供示例的

**Comment by loserZhang** [comment]
好的谢谢
