### ISSUE TITLE
FuturesOrder.size as int

### ISSUE THREAD

**Issue by davidevincenzi** [gateio/gateapi-python#53]
Hi. Why is the [FuturesOrder.size](https://github.com/gateio/gateapi-python/blob/master/docs/FuturesOrder.md) an int?
I'm able to buy Futures for fractions in the website, not sure why I'm limited to integers in the API 🤔.

Thanks

**Comment by revilwang** [comment]
The fractions you input in the website actually is currency amount, not size, which will turns to int when committing requests to the server. For example, the response of `https://api.gateio.ws/api/v4/futures/usdt/contracts/BTC_USDT` has a field `quanto_multiplier`, which is 0.0001 for BTC_USDT. It means 1 size = 0.0001 BTC. If you input 0.1 BTC in the website, the actual request sent to the server is size 0.1/0.0001 = 1000 size

**Comment by davidevincenzi** [comment]
I see, thank you @revilwang for the very quick answer! 👍
