### ISSUE TITLE
杠杆交易全仓/逐仓？

### ISSUE THREAD

**Issue by HFLeon** [gateio/gateapi-python#56]
杠杆交易，下单接口：POST /spot/orders
如何区分全仓还是逐仓？

**Comment by revilwang** [comment]
全仓的支持还未上线，现在只有逐仓，晚些时间会上线

**Comment by HFLeon** [comment]
好的，全仓大概什么时间节点会上线

**Comment by revilwang** [comment]
就这几天，到时候文档 SDK 会同步更新

**Comment by HFLeon** [comment]
好的，谢谢

**Comment by revilwang** [comment]
全仓杠杆支持已推送， `pip install --upgrade gate-api` 升级到最新的 4.21.1 就可以使用全仓相关操作，相关文档详见 [这里](https://www.gateio.ch/docs/apiv4/zh_CN/index.html#fd6ce2a756) 和 [这里](https://www.gateio.ch/docs/apiv4/zh_CN/index.html#20f87be968)

**Comment by HFLeon** [comment]
全仓杠杆交易设置了auto_borrow，就不能再设置auto_repay了吧，还是要通过/margin/auto_repay来设置账户的自动还款

**Comment by revilwang** [comment]
1. 全仓里两个字段的确不能同时开启

**Comment by HFLeon** [comment]
好的，这里全仓自动借入的部分，需要通过全仓杠杆还款[/margin/cross/repayments]来归还对吧

**Comment by revilwang** [comment]
嗯，是这样子，还可以通过下单设置 account=cross_margin, auto_repay=true，成交之后得到的币会优先用于还款全仓的借入
