### ISSUE TITLE
How can I buy total usdt 100$ coins at the last sold price?

### ISSUE THREAD

**Issue by fmsimsek** [gateio/gateapi-python#57]
Hello sir,

How can I buy total usdt 100$ coins at the last sold price?

**Comment by fmsimsek** [comment]
example SAFEMARS

**Comment by revilwang** [comment]
We have usage example [here](https://github.com/gateio/gateapi-python/blob/master/docs/SpotApi.md#create_order) and [here](https://github.com/gateio/gateapi-python/blob/master/example/spot.py#L41)

If you have 100 USDT, you can just create an `gate_api.Order(currency_pair='SAFEMARS_USDT', side='buy', amount='<how much SAFEMARS you want>', price='<some price you need to fill yourself>')` and use `SpotApi.create_order` to buy SAFEMARS from USDT.
