### ISSUE TITLE
How to determine the real withdrawn amount for a withdrawal

### ISSUE THREAD

**Issue by Programmierus** [gateio/gateapi-python#58]
I don't see any way to determine the real withdrawn amount for a (submitted) withdrawal after the withdrawal fee has been applied.

Nor it is possible to determine the withdrawal fee, because list_withdraw_status() method returns only one record per token and in multi-chain case fees differ from chain to chain. Hard-coding a fixed fee isn't an option either since they change on an hourly basis.

Please advise.

**Comment by revilwang** [comment]
I'll report this issue back to the server implementation.

**Comment by revilwang** [comment]
We've add a new `withdraw_fix_on_chains` dict returned which contains all fees on multiple chains.

`pip install --upgrade gate-api==4.21.5` to use the new field

**Comment by Programmierus** [comment]
Thank you for the update. Will try and report!

**Comment by Programmierus** [comment]
Works
