### ISSUE TITLE
撤单频率有限制吗

### ISSUE THREAD

**Issue by pumpthis** [gateio/gateapi-python#6]
撤单频率有限制嘛？{'label': 'METHOD_NOT_ALLOWED', 'message': 'Cancel order too fast, please wait 1 min and try again.'}是什么触发的？

**Comment by pumpthis** [comment]
@revilwang

**Comment by revilwang** [comment]
按用户限制，每分钟内最多 1000 次

**Comment by pumpthis** [comment]
假如我逐个撤销订单 而不是选择全撤接口 也会有频率限制吗？

**Comment by pumpthis** [comment]
我在一个账户里做七个品种的做市 margin账户撤单 每分钟内加起来大约一两百次 连续五六分钟后 也收到限制了

**Comment by revilwang** [comment]
批量算一个用户的一次接口调用，跟订单数量无关

**Comment by revilwang** [comment]
现在的限制策略会隔一分钟清一次，但是如果在一分钟结束之前还有调用，会继续延长一分钟，所以会导致连续几分钟之后会被限制的情况。建议你尽量考虑批量少次调用，我们再优化一下这个策略

**Comment by pumpthis** [comment]
好的 多谢！

**Comment by pumpthis** [comment]
我统计了一下 跑了三个品种 一分钟总共调用撤单接口60次不到 就被冻住了...建议您也用个小账户试一下...我感觉是撤单好像不太对...

**Comment by pumpthis** [comment]
或者可能是因为我调用了margin账户的撤单？不知道现货的撤单是不是这样

**Comment by revilwang** [comment]
嗯，我们再排查下

**Comment by revilwang** [comment]
@pumpthis 接口调用计数限制方法已改进。如果您持续在调接口，建议先等1分钟将原先的计数清零，再重新调用。

目前的逻辑每分钟都会清理一次计数。依然是按单个用户每分钟最多1000次撤销。杠杆交易接口复用现货的交易接口，所以两个账户（现货和杠杆）的两种操作（单个和批量）会使用同一个计数器来做限制

**Comment by pumpthis** [comment]
谢谢！刚才跑了二十分钟 所有做市的脚本都没有撤单超频了，单子能一直挂上了，感谢
