### ISSUE TITLE
How to get all list_currency 

### ISSUE THREAD

**Issue by fmsimsek** [gateio/gateapi-python#60]
Hello sir,

i can use list_currencies function but i can'nt get only currency name.
How can i get  only  all list currency name ?
example btc_usdt, ltc_usdt, bnb_usdt etc..
thank you.

**Comment by revilwang** [comment]
I think you means `list_currency_pairs`

**Comment by fmsimsek** [comment]
> I think you means `list_currency_pairs`

No , list_currency_pairs output as bellow but i get  wanna only 'id' value

{'amount_precision': 4,
 'base': 'ALPHR',
 'buy_start': 0,
 'fee': '0.2',
 'id': 'ALPHR_USDT',
 'min_base_amount': None,
 'min_quote_amount': '1',
 'precision': 4,
 'quote': 'USDT',
 'sell_start': 0,
 'trade_status': 'tradable'}]

**Comment by fmsimsek** [comment]
i solved this problem  thank you

```
 api_response = api_instance.list_currency_pairs()
     for i in api_response:
        print(i.id)
```

**Comment by revilwang** [comment]
one line code for python

```python
currency_pairs = [x.id for x in api_instance.list_currency_pairs() if x.trade_status != 'untradable']
```
