### ISSUE TITLE
查询单个订单详情

### ISSUE THREAD

**Issue by HFLeon** [gateio/gateapi-python#61]
GET /spot/orders/{order_id}

order_id：用户创建时指定的自定义 ID（即 text 字段），刚下单然后又撤销的定单就查不到了

label:CLIENT_ID_NOT_FOUND

**Comment by HFLeon** [comment]
通过SDK下的单，然后在PC页面上撤的单，再通过SDK去查就查不到了

**Comment by revilwang** [comment]
未成交的订单只有1分钟查询有效期

**Comment by HFLeon** [comment]
啊？ 那这个就没办法查到了吗

**Comment by revilwang** [comment]
是的，所有0成交的订单不入库，在撤单之后只保留1分钟的有效查询时间，之后就获取不到了

**Comment by HFLeon** [comment]
2021-06-29 03:00:01  创建订单后立即成交

**Comment by revilwang** [comment]
现在能查到吗？

**Comment by HFLeon** [comment]
现在已经过了半个小时，用订单 ID是可以查到的

**Comment by revilwang** [comment]
请提供具体的 order id ，我们排查一下

**Comment by HFLeon** [comment]
58314910021

**Comment by revilwang** [comment]
已成交的订单只会保留 1 小时的查询时效，相关人员在排查问题时已超过该时效，问题未定位。

订单刚刚创建完成的时候，有可能存在刚开始的短时间内无法查询的情况，如果 10s 后仍然查询不到，请及时提供对应的订单 id
