### ISSUE TITLE
USER_LOAN_EXCEEDED

### ISSUE THREAD

**Issue by HFLeon** [gateio/gateapi-python#63]
全仓杠杆支持的币种列表 
 GET /margin/cross/currencies
` {
        "name": "DOGE", 
        "rate": "0.000039", 
        "prec": "0.000001", 
        "discount": "1", 
        "min_borrow_amount": "200", 
        "user_max_borrow_amount": "10000", 
        "total_max_borrow_amount": "100000", 
        "price": "0.256202"
  }`
风险率2.039，再借就报这个错

**Comment by HFLeon** [comment]
在PC页面上就可以借，这里是否有bug？

**Comment by revilwang** [comment]
请提供具体的借入参数

**Comment by HFLeon** [comment]
currency='DOGE’, amount=393.214571

**Comment by revilwang** [comment]
问题确认，正在修复，修正之后会在本 issue 更新

**Comment by revilwang** [comment]
该问题已修复上线
