### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by HFLeon** [gateio/gateapi-python#64]
最近时有发生这样的500错误
`ERROR Gate api exception, label: SERVER_ERROR, message: Internal server error`

`ERROR Exception when calling MarginApi->get_cross_margin_account: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 29 Jun 2021 04:09:50 GMT', 'Content-Type': 'text/html', 'Content-Length': '174', 'Connection': 'keep-alive', 'Server': 'openresty'})
HTTP response body: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>openresty</center>
</body>
</html>`

**Comment by HFLeon** [comment]
repay_cross_margin_loan 一直500 是挂了吗？
<img width="1126" alt="QQ20210630-164120@2x" src="https://user-images.githubusercontent.com/4714695/123930166-0f639780-d9c2-11eb-93fd-212d5650efb6.png">

**Comment by revilwang** [comment]
这个问题我们确认下

**Comment by revilwang** [comment]
麻烦提供下具体的还款参数？

**Comment by revilwang** [comment]
有一种可能是提供的 amount 参数格式是科学技术法，可以先尝试检查下输入的参数是否存在类似的情况

**Comment by HFLeon** [comment]
currency='fil', amount=8.261830242682716

**Comment by revilwang** [comment]
最近的请求是否恢复正常？

**Comment by HFLeon** [comment]
最近一小时没发现异常，这个是什么原因呢？

**Comment by HFLeon** [comment]
但现在  get_cross_margin_account  500
<img width="1212" alt="QQ20210630-180546@2x" src="https://user-images.githubusercontent.com/4714695/123942559-d6312480-d9cd-11eb-8f87-7e3bfd6c49d9.png">

**Comment by revilwang** [comment]
应该已经恢复了，现在还会继续有 server_error 吗

**Comment by HFLeon** [comment]
恩，目前没有了，这两个是什么情况呢？

**Comment by revilwang** [comment]
全仓杠杆引擎出现了瓶颈，导致一段时间的请求没有正常处理，大概在北京时间 6 月 30 号下午 6 左右恢复了

**Comment by HFLeon** [comment]
好的，谢谢
