### ISSUE TITLE
撤单频率

### ISSUE THREAD

**Issue by HFLeon** [gateio/gateapi-python#65]
全仓杠杆撤单频率限制是怎样的？ SDK连发两次撤单请求都没撤掉，14s之后再次请求才被撤掉

**Comment by revilwang** [comment]
具体撤单不成功，返回的错误是什么？全仓杠杆跟逐仓、现货的撤单频率是共享的，每分钟不超过 5000 次都是可以的

**Comment by HFLeon** [comment]
> 具体撤单不成功，返回的错误是什么？全仓杠杆跟逐仓、现货的撤单频率是共享的，每分钟不超过 5000 次都是可以的

label:CLIENT_ID_NOT_FOUND

**Comment by revilwang** [comment]
这个不是限频造成的。有当时的请求日志记录保留吗？可以邮件发一份跟该 client_id 相关的创建和撤单请求日志

**Comment by HFLeon** [comment]
这个已经过了一小时，大概在今天早上的8:24，复盘分析的时候发现的，日志现在没了，参数是 currency_pair='ETH_USDT' client_id='t-162630868552364'

**Comment by revilwang** [comment]
后台看到了对应的请求记录，这个问题我们记录下，看看怎么样更好处理下。这边建议是可以尝试在下单成功之后打算立即撤单，可以多重试几次

**Comment by HFLeon** [comment]
好的，谢谢

**Comment by revilwang** [comment]
我们对基于 client_id 的操作做了一些优化，可以后续继续观察是否会常出现 CLIENT_NOT_FOUND 的错误
