### ISSUE TITLE
Buying with USDT

### ISSUE THREAD

**Issue by Liutzik** [gateio/gateapi-python#69]
Hello!

Is there a method to create an order to buy with USDT, for example BTC_USDT. Can I place an order so that amount={to be in USDT}?

Thanks!

**Comment by revilwang** [comment]
[Here](https://github.com/gateio/gateapi-python/blob/master/example/spot.py#L41) is an example to create an order. Set `currency_pair` to `BTC_USDT` and `side` to `buy`
