### ISSUE TITLE
撤单频率又被限制了

### ISSUE THREAD

**Issue by pumpthis** [gateio/gateapi-python#7]
你好！
我目前在gate的七个交易对上做市（日交易量达到60btc了，还能往上加）做到昨天都很顺畅，但是今天11：49撤单又被限频了。。
我的uid是2541076
我的七个程序，每个程序每分钟调用撤单接口（参数有account=margin）撤单10~30次。今天做到11：49之前都正常，11：49开始返回{'label': 'METHOD_NOT_ALLOWED', 'message': 'Cancel order too fast, please wait 1 min and try again.'}，此后就一直这个状态。
然后我关掉所有程序，等待了十分钟，重启其中一个程序后，第一次撤单 依然返回{'message': 'Cancel order too fast, please wait 1 min and try again.', 'label': 'METHOD_NOT_ALLOWED'}

**Comment by pumpthis** [comment]
@revilwang

**Comment by pumpthis** [comment]
我也想在gate上挂更多的单增加深度，做大利润，但限频有点郁闷啊...而且我也是正常撤单 感觉频率真的不高

**Comment by revilwang** [comment]
抱歉带来困扰，我帮您确认下问题

**Comment by revilwang** [comment]
问题已处理

**Comment by pumpthis** [comment]
感谢
