### ISSUE TITLE
With_id

### ISSUE THREAD

**Issue by ibmua** [gateio/gateapi-python#71]
https://github.com/gateio/gateapi-python/blob/master/docs/FuturesApi.md#list_futures_order_book

IRL the example doesn't work.

``
Gate api exception, label: INVALID_PARAM_VALUE, message: Invalid request parameter `with_id` value: False
``

Version gate_api-4.21.6-py3-none-any.whl

**Comment by revilwang** [comment]
`urllib` won't lowercase python boolean to `true` or `false` in request parameters and the server only accepts lowercase boolean, try to set `with_id` to `false` or remove it totally
