### ISSUE TITLE
SpotApi->list_currency_pairs这个函数今天突然不能用了！报以下错误!

### ISSUE THREAD

**Issue by yazhoushi** [gateio/gateapi-python#72]
Exception when calling SpotApi->list_currency_pairs: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 27 Sep 2021 04:57:55 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'openresty'})
HTTP response body: {"label":"MISSING_REQUIRED_HEADER","message":"Missing required header: Timestamp"}

**Comment by revilwang** [comment]
该问题在解除对这该接口单独的限速时引入，已恢复

**Comment by fertingoff** [comment]
Have exactly the same issue. Any ideas?

**Comment by revilwang** [comment]
create_order is a private endpoint. You need to [setup your API key](https://github.com/gateio/gateapi-python/blob/master/docs/SpotApi.md#create_order) and secret before invoking it.

**Comment by fertingoff** [comment]
Thank you so much. I did it 
````
import gate_api
from gate_api import ApiClient, Configuration, Order, SpotApi

````
````
        config = Configuration(key=GATE_IO_API_KEY, secret=GATE_IO_SECRET)
        spot_api = SpotApi(ApiClient(config))
````
