### ISSUE TITLE
Problem with futures order details

### ISSUE THREAD

**Issue by tomm1gun** [gateio/gateapi-python#80]
Hi, I am having a problem when inserting a float value on 'size'
order = FuturesOrder(contract=contract, size=0.75, price=price1)
I took a closer look at this document and found that you can only enter integer values, what should i do?
https://github.com/gateio/gateapi-python/blob/master/docs/FuturesOrder.md

Thanks and have a good day!

**Comment by revilwang** [comment]
I suppose you are trying to input order amount. Size parameter is the contract size. There is a `quanto_multiplier` in the contract detail.`order_amount = size * contract.quanto_multiplier`

**Comment by tomm1gun** [comment]
Ok thanks, one more question, is there any istruction to acquire technical data?(volume, moving average...)

**Comment by revilwang** [comment]
API provides only basic data like trades, candlesticks, etc.

**Comment by tomm1gun** [comment]
ok, have a good day.
