### ISSUE TITLE
Certain data can't be downloaded from history center

### ISSUE THREAD

**Issue by neowod** [gateio/gateapi-python#82]
[https://www.gate.io/developer/historical_quotes](url) Choose data as candlesticks, contract as BTC_USDT, time as 2021-9 and click download you'll see an error as such. I wrote some codes to batch download them even if I set time until 2021-8, still couldn't make it, that being said there are some other data missing. I don't know what exact periods of data they are, since I batch download them from all contracts and all time since 2019-11, even this BTC_USDT 2021-9 problem was found by my friend.
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>futures_usdt/candlesticks_1h/202109/BTC_USDT-202109.csv.gz</Key>
<RequestId>2JXGZDVR6ANV2PY0</RequestId>
<HostId>GH4VaHOEaEpuR0bUKmRWutNib8HEaO8QU3cnKSrlbs/U+Ma6Llx+oSZ5bitiXEB7Q0cK0kwvJ2E=</HostId>
</Error>
```

**Comment by revilwang** [comment]
The missing data has been uploaded.
