### ISSUE TITLE
Important - How to close a Futures order/position?

### ISSUE THREAD

**Issue by MrCanan** [gateio/gateapi-python#85]
Hi,

How can I close an order/position with the Futures API? (I mean like if I click on "Market" on the web UI)
I can create without problem a Futures order with "FuturesOrder" and "create_futures_order" and get its id (and other information like size).

![Screenshot 2021-12-12 12 28 04](https://user-images.githubusercontent.com/26158345/145710424-626b4c83-6479-4a32-8386-44ee1c7752cf.png)

Thank you in advance,
Best regards.

**Comment by revilwang** [comment]
I think you are trying to close a position. To close a position, you need to create a close order. When it is filled, your position will be closed. To create a close order, set `close` to true and `size` to 0 (which is documented [here](https://github.com/gateio/gateapi-python/blob/master/docs/FuturesOrder.md))

**Comment by MrCanan** [comment]
Thank you, I did not see it ^^
