### ISSUE TITLE
Missing required header: Timestamp

### ISSUE THREAD

**Issue by elier** [gateio/gateapi-python#87]
the example list_currency_chains returns
```
body: {"label":"MISSING_REQUIRED_HEADER","message":"Missing required header: Timestamp"}
```
https://github.com/gateio/gateapi-python/blob/master/docs/WalletApi.md#list_currency_chains

Python 3.9.8
gate-api==4.23.0

**Comment by revilwang** [comment]
Fixed from the server side.

**Comment by elier** [comment]
it's working now .. lovely .. thanks
