### ISSUE TITLE
撤单被限制

### ISSUE THREAD

**Issue by pumpthis** [gateio/gateapi-python#9]
你好！我的uid是2541076

交易了七天 交易量做到了1846.80694 BTC 103417495.03 CNY 

我还是七个品种 杠杆账户交易撤单接口撤单，每分钟其实加起来不会超过300次的。

从今天04：50左右开始，又一直显示{'message': 'Cancel order too fast, please wait 1 min and try again.', 'label': 'METHOD_NOT_ALLOWED'

请问能不能解决一下...行情这么好 有点郁闷... 目前我停掉所有程序后五六分钟 重启了下 还是返回Cancel order too fast

**Comment by pumpthis** [comment]
@revilwang

**Comment by revilwang** [comment]
好的，我先帮你恢复掉，然后尝试下能不能复现这个问题，带来困扰实在抱歉

**Comment by pumpthis** [comment]
感谢 恢复成功了

**Comment by pumpthis** [comment]
其实 可以弄一个账户 一分钟请求5000次 手动超频 (假如能的话...) 然后看看 再过四五分钟 重新请求撤单这个号 是不是还在超频... 我这边发现 好像超频了没法自动恢复 是其中一个问题

**Comment by revilwang** [comment]
你好，问题我们基本定位了，会尽快优化。这期间如果有问题，暂时只能麻烦你这边提 issue 人工来帮你恢复了

**Comment by pumpthis** [comment]
好的 太感谢！

**Comment by pumpthis** [comment]
我有问题都会这这边第一时间提交的

**Comment by revilwang** [comment]
超限的问题已经成功复现并且修复了，该 issue 先关闭，如果还有问题再新开
