### ISSUE TITLE
API

### ISSUE THREAD

**Issue by amirreza2400** [gateio/gateapi-python#90]
Hello good time
I want to use your API so that I can get services from you for my . How should I provide an address for each user? I can manage that each user has his own address so that he can make a deposit and trade.

**Comment by revilwang** [comment]
I would suggest creating sub accounts for  each user and transfer funds into their account. Every sub account can have his or her own API key to operate separately. But sub account cannot operate deposits and withdrawals. You have to use the main account to do so.
