### ISSUE TITLE
Withdrawal fee

### ISSUE THREAD

**Issue by jM9sr1vsH7nOZ8Y5** [gateio/gateapi-python#93]
Is it possible to retrieve the fee associated with a withdraw? Calling WalletAPI/list_withdrawels with _preload_content=False, the HTTP-response returns a field "fee". However, this field is not available in the returned LedgerRecord.

**Comment by revilwang** [comment]
Thanks for reporting. I'll add this field into LedgerRecord on next update ASAP

**Comment by elyase** [comment]
sorry for hijacking the issue but could you also export the withdrawal address? Unfortunately [the listings page](https://www.gate.io/coins) is not always updated. 

Would also close this issue:
https://github.com/gateio/gateapi-python/issues/88

**Comment by revilwang** [comment]
Sorry for kept you waiting so long, but newer version 4.23.2 has been published with `fee` attribute added.

**Comment by jM9sr1vsH7nOZ8Y5** [comment]
Thank you very much! I will close this issue.

**Comment by abirqurish** [comment]
Good
