### ISSUE TITLE
ordering at the market price

### ISSUE THREAD

**Issue by Monalith** [gateio/gateapi-python#99]
Hello Folks,
I have quite some experience at Python but not gate.io api.

So my question is how to make an order at the market price.

Yes I can get the last price but at very versatile points I can not optimize the limit in a good way.

What I do now is to open an order with 1.001*price and follow the status to make sure that it is closed to make sure that I buy it but I am not sure if this is the best way.

So any ideas ? At binance there is the order_market_buy command.

Anything similar ?

Thank you,
Eren Uyanik

**Comment by revilwang** [comment]
Spot market order has been supported in 4.34.0 version

**Comment by csst0286** [comment]
Hi I am having the same question for java using "io.gate:gate-api:6.25.1", how can I buy spot in market price? Could someone support me with this? Thank you in advance!
